name: BreakerConfiguration
description: Switching arrangement for a bay.
attributes:
- name: SINGLE_BREAKER
  description: Single breaker.
- name: BREAKER_AND_A_HALF
  description: Breaker and a half.
- name: DOUBLE_BREAKER
  description: Double breaker.
- name: NO_BREAKER
  description: No breaker.
