name: BusbarConfiguration
description: Busbar layout for a bay.
attributes:
- name: SINGLE_BUS
  description: Single bus.
- name: DOUBLE_BUS
  description: Double bus.
- name: MAIN_WITH_TRANSFER_BUS
  description: Main bus with transfer bus.
- name: RING_BUS
  description: Ring bus.
