name: Create grpc-c-builder image

on: workflow_dispatch

jobs:
  build_grpc_c_builder:
    runs-on: ubuntu-latest
    container:  hashicorp/packer:1.11
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Packer Version
        run: |
          packer version

      - name: Create zepben/grpc-c-builder
        run: |
          apk add docker tar
          mkdir /build
          export PACKER_CONFIG_DIR=/build
          cd c/builder-container
          packer init alpine-protoc.pkr.hcl
          packer validate alpine-protoc.pkr.hcl
          packer build -on-error=abort -var dockerhub_user=$DOCKER_HUB_USER -var dockerhub_pw=$DOCKER_HUB_ACCESS_TOKEN alpine-protoc.pkr.hcl
        shell: bash
